name: Simple Build

on:
  push:
    branches:
      - main
      - challenge_dev
  pull_request:
    branches:
      - main
      - challenge_dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "🎉 GitHub Action is working on ${{ github.ref }}"
